#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
title: Aggie '23
# Short bio or description (displayed in the header)
description: An Aggie in the Class of 2023

#
# !! DON'T EDIT BELOW THIS MESSAGE
#
# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# This is for my 460 Lab.

theme: jekyll-theme-cayman